name: Publish Docker image
on:
  push:
    branches:
      - 'master'
jobs:
  push_to_registry:
    name: Push Docker image to Aliyun Registry
    runs-on: ubuntu-latest
    # permissions:
    #   packages: write
    #   contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Print Name
        run: echo "The id was ${{ github.actor }}"
      - name: Print ENV
        run: echo "The name was ${{ secrets.ALINAME }}"
      - name: Log in to Aliyun Registry
        uses: docker/login-action@v1
        with:
          registry: registry.us-west-1.aliyuncs.com
          username: ${{ secrets.ALINAME }}
          password: ${{ secrets.ALIPASS }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.us-west-1.aliyuncs.com/test_gg/lost:etcd